### ISSUE TITLE
Can't add multiple classes with className

### ISSUE THREAD

**Issue by usame-algan** [electerious/basicLightbox#13]
Im trying to pass multiple classes to className like this:

`className: 'class1 class2'`

But getting the following error:

`DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('class1 class2') contains HTML space characters, which are not valid in tokens.`

Is there something Im missing? An option would be using the [Spread Operator](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Spread_syntax) like shown here: https://stackoverflow.com/a/36486683/6085256

**Comment by electerious** [comment]
You're right. It should be `.classList.add('a', 'b')` instead of `.classList.add('a b')`. We could use the spread operator or a similar technique for this.

**Comment by electerious** [comment]
Fixed! https://github.com/electerious/basicLightbox/blob/master/CHANGELOG.md#403---2018-05-18
