### ISSUE TITLE
Proposal: passing a node to create

### ISSUE THREAD

**Issue by funkyfuture** [electerious/basicLightbox#15]
i have a scenario where i would rather pass a programatically node to `create` than an html string. would you accept a patch providing this functionality?

**Comment by electerious** [comment]
Sounds like a good addition. I'm always converting Nodes to Strings using `.outerHTML`, but that's kinda stupid. I don't know why I never had the idea to simply support Nodes directly 🤔

**Comment by electerious** [comment]
basicLightbox v5 is out and includes node elements and templates in `.create()`. Check out all the examples. It's very powerful and yet super simple to use. Thanks for the suggestion!

https://github.com/electerious/basicLightbox/blob/master/CHANGELOG.md#500---2018-09-23
