### ISSUE TITLE
IE11 Support?

### ISSUE THREAD

**Issue by NoxiousSolitary** [electerious/basicLightbox#23]
The documentation states that basicLightbox is compatible with Internet Explorer 11. However, the examples on the product page don't work in Internet Explorer 11.
https://basiclightbox.electerious.com/

IE Version Tested: 11.523.17134.0

The main console error that appear when clicking on any of the 'Run' buttons to demo the project is below:

`Object doesn't support property or method 'from'`
`main.js (1,5323)`

The documentation also has examples with arrow functions, which aren't supported in IE11.

Could the documentation be updated with a revised list of supported browsers, or clearer explanations for what's supported in the examples?

**Comment by electerious** [comment]
Hey @NoxiousSolitary 

basicLightbox supports IE11 [with polyfills](https://github.com/electerious/basicLightbox#requirements). The website of basicLightbox itself has no polyfills implemented. Same applies to the demos.

Demo code is written in modern JS, which isn't supported by IE11 either. You can use the website of Babel to convert it to a compatible version: https://babeljs.io/repl
