### ISSUE TITLE
Gallery Support

### ISSUE THREAD

**Issue by marbuser** [electerious/basicLightbox#24]
Hey there,

I really like basicLightbox but the one feature I feel it's lacking is a gallery (i.e multiple pics with forward and back buttons).

I'm also using the swiper carousel so not sure if there is any easy way for me to integrate it with that.

**Comment by electerious** [comment]
It's not planned to integrate a gallery directly into basicLightbox as buttons, animations and gestures are beyond basic.

basicLightbox however lets you display anything you want. You can simply use a carousel of your choice.

1. Create a lightbox with the carousel markup: https://github.com/electerious/basicLightbox#createcontent-opts
2. Use the `onShow` option to initialise the carousel

**Comment by MaluNoPeleke** [comment]
Can you show that in a demo? I don't have enough knowledge/experience to come up with it by myself.
