### ISSUE TITLE
Lightbox from attributed elements not possible out of the box?

### ISSUE THREAD

**Issue by jenstornell** [electerious/basicLightbox#30]
Let's say I have 30 images in my content and I want to show them in a lightbox.

Then I would prefer something like this:

```js
const instance = basicLightbox.create({
  selector: 'img.lightbox'
});
```

Something like above would then find all the images that has the class `lightbox` and then create a lightbox for all of them.

That's not possible today?

**Comment by electerious** [comment]
That's not possible, but you can achieve almost the same with a loop:

```js
document.querySelectorAll('img.lightbox').forEach((img) => {
  const instance = basicLightbox.create(img);
})
```
