### ISSUE TITLE
Adding an ajax loading graphic whilst a slow iframe is being retrieved

### ISSUE THREAD

**Issue by arkid** [electerious/basicLightbox#34]
I have the lightbox calling an external site via the iframe functionality and this remote server is always rather slow returning a page.   Whilst that is waiting I need to show some feedback to the user.  Are there any examples of doing this with a loading graphic ?

**Comment by electerious** [comment]
There's no example, but basicLightbox can contain all types of elements. You can therefore look for iframe preloading/loader examples and use them inside basicLightbox. Similar to the elements created and used here: https://codepen.io/electerious/pen/wEZmQy

**Comment by arkid** [comment]
To clarify, I have no control of the iframe source so this would have to be an iframe rendered dynamically along with some other element that I place on top of the iframe such as a loading wheel.    

Can I parse iframe code to the lightbox as part of some custom content and it work just as if using an iframe with the _standard_ approach you've made for using iframes within basicLightbox?

**Comment by electerious** [comment]
> Can I parse iframe code to the lightbox as part of some custom content and it work just as if using an iframe with the standard approach you've made for using iframes within basicLightbox?

That should work. You might need to tweak the position of the iframe, but there's nothing that prevents you from passing a spinner and an iframe to basicLight.

```js
import * as basicLightbox from 'basiclightbox'

const instance = basicLightbox.create(`
    <div class="modal">
        <div class="spinner"></div>
        <iframe src="https://www.youtube.com/embed/E1oZhEIrer4" width="560" height="315" frameborder="0"></iframe>
    </div>
`, {
    onShow: (instance) => {
        // Hide iframe or preload it and show spinner in the meanwhile
        // https://stackoverflow.com/questions/34708261/load-iframe-with-spinner
    }
})

instance.show()
```

**Comment by arkid** [comment]
This doesn't work quite right as the iframe shows instantly with the remote server source loading away for some seconds.   As the iframe appears instantly the onShow condition is met and the spinner I've setup hides itself basically as soon as the lightbox appears when the user activates it via a button on the main page.

**Comment by adam-jones-net** [comment]
Does anyone have any further advice on this ?  @electerious is there anything you can recommend following my last response ?
