### ISSUE TITLE
Handling <picture> tag

### ISSUE THREAD

**Issue by 8lall0** [electerious/basicLightbox#35]
When i try to put a <picture> tag, since i want to support webP, the image acts weird.

**Comment by electerious** [comment]
Can you provide a reproducible demo or a detailed explanation of what you're doing  and what's happening?

**Comment by 8lall0** [comment]
Since the <picture> tag is not handled, if an image is bigger than the viewport it simply covers all.
I took a look at your code, you only take care of direct children (>img, >iframe etc.) and, since it's not handled, it doesn't append the correct modifier class (--img etc.).

Maybe i found a way, do you accept pull requests?

**Comment by electerious** [comment]
> Maybe i found a way, do you accept pull requests?

Sure!

**Comment by 8lall0** [comment]
Done :) i close this issue!
