### ISSUE TITLE
Close with esc key

### ISSUE THREAD

**Issue by JiveDig** [electerious/basicLightbox#38]
Thanks for such a great API.

This feature is pretty easy to add, which I've been doing in `onShow` like this:

```
onShow: (instance) => {
	// Close when hitting escape.
	document.onkeydown = function(evt) {
		evt = evt || window.event;
		var isEscape = false;
		if ( "key" in evt ) {
			isEscape = ( evt.key === "Escape" || evt.key === "Esc" );
		} else {
			isEscape = ( evt.keyCode === 27 );
		}
		if ( isEscape ) {
			instance.close();
		}
	};
},
```

...but this seems to be the standard for modals, I wonder if it make sense in the official script?

**Comment by electerious** [comment]
You have to consider that basicLightbox just displays whatever you want in the middle of the screen. This might be something that already uses the ESC key. Or you use basicLightbox on a website with a keyboard navigation where ESC is already assigned to a different function. I don't like to make assumptions about keybindings and therefore don't handle them. Instead I like to provide an API that makes it easy to add the features you want in a way that fits into your use-case. ESC handling is easy to add and therefore not a part of the lightbox itself.

**Comment by JiveDig** [comment]
Makes sense to me. Thanks for the explanation 👍.

**Comment by jayjarosz** [comment]
Kirby CMS uses basicLightbox in their StarterKit and I found this thread today while searching for how to add the ESC key functionality. I'm adding the solution as a comment in case any other Kirby users end up here.

Solution: You need to replace the StarterKit's code in `/assets/index.js` with this:

```
Array.from(document.querySelectorAll("[data-lightbox]")).forEach(element => {
  element.onclick = (e) => {
      e.preventDefault();

      // Create the basicLightbox instance
      const instance = basicLightbox.create(`
          <img src="${element.href}">
      `);

      // Show the lightbox
      instance.show();

      // Add keydown event listener to close on ESC key
      const handleEsc = (event) => {
          if (event.key === "Escape" || event.keyCode === 27) {
              instance.close();
              document.removeEventListener("keydown", handleEsc);
          }
      };

      document.addEventListener("keydown", handleEsc);
  };
});
```
