### ISSUE TITLE
non minified version on dist folder

### ISSUE THREAD

**Issue by joseehilton147** [electerious/basicLightbox#42]
Hi, great plugin!

Can you add a non minified version inside dist folder too? I'm using your plugin with Rider from JetBrains, but to auto-detect need to be a non minified version.

**Comment by electerious** [comment]
Hi, it's currently not planned to add a non-minified version to the dist, but maybe it's possible to adjust the package.json so other scripts know were the src is located.

A PR is welcome, but I will close this issue as it's not planned from my side.
