### ISSUE TITLE
Closing opened iFrame

### ISSUE THREAD

**Issue by jshster** [electerious/basicLightbox#43]
Hey guys,
Just wondering if you can offer any suggestions on how to close a BasicLightbox popup that is an iFrame, without clicking on the space outside the popup? 

I've tried getting all sorts of variations - using parent, top, window..... none of them seem to be access the calling window. 

But perhaps the easier question is I know I need to call the close() method to close the window.  But I need to bind that close() call to the basicLightBox instance that's been created.  

Can anyone help?
Thanks
Josh

**Comment by electerious** [comment]
I think that's possible somehow, but the question is more about the communication between a site and an iframe, not about basicLightbox. The API should provide everything you need once you got the communication working.

Related: https://github.com/electerious/basicLightbox/issues/41
