### ISSUE TITLE
Scrolling on open

### ISSUE THREAD

**Issue by michaelroy-yvr** [electerious/basicLightbox#44]
I'm having the following issue.

I've implemented basicLightBox on a long webpage - and whenever i trigger a lightbox, the page scrolls back to the top of the page, breaking the experience for the user.

Any possible fixes to stop the page from scrolling to the top?

**Comment by electerious** [comment]
This has something to do with the implementation of how you trigger the lightbox, not with basicLightbox itself. I guess that you're using a link with a href="#", which will scroll the page up when the event isn't canceled. If that's the case then reconsider the element you're using or stop the event propagation. Related terms to google are "Event Propagation" and "Event Bubbling". Hope that helps.
