### ISSUE TITLE
.99 Opacity bug

### ISSUE THREAD

**Issue by jimblue** [electerious/basicLightbox#7]
Hi,

First thanks for this sharp and clean plugin 😄 !

I'm just wondering why you use .99 opacity for the main wrapper. All texts behind are slightly visible because of that. Is it possible to run opacity to 1?

**Comment by electerious** [comment]
Animating from .01 to .99 reduces the amount of repaints. I first thought it's a good idea, but sometimes the background is slightly visible. Will be fixed with the next version!

**Comment by jimblue** [comment]
@electerious ok great!
Thanks for the explanations.

**Comment by electerious** [comment]
https://github.com/electerious/basicLightbox/blob/master/CHANGELOG.md#303---2017-08-08
