### ISSUE TITLE
feature request: hash url

### ISSUE THREAD

**Issue by jimblue** [electerious/basicLightbox#8]
Hi!

First thank you for this very nice piece of code, sharp and clean!

Wondering if you could consider adding `hash`navigation for the lightbox.

This script to do this kind of job but using jQuery:

https://github.com/sachinchoolur/lightGallery/blob/master/modules/lg-hash.js

What do you think?

**Comment by jimblue** [comment]
Also found this interesting library: https://github.com/EastingAndNorthing/urlhash

**Comment by electerious** [comment]
I try to keep basicLightbox as light and clean as possible. Navigation is complex when you want to implement something that works in all cases (e.g. webapps). It always depends on where you use it.

The good thing: You can easily implement it by yourself using the scripts you mentioned. Just use the API of basicLightbox when the hash changes.

**Comment by jimblue** [comment]
Sure I understand 😄 !

Thanks for answering @electerious
