### ISSUE TITLE
change npm main to src

### ISSUE THREAD

**Issue by jimblue** [electerious/basicLightbox#9]
Hi again @electerious,

I'm apparently the only one around haha 😄  !

I was wondering if it's possible to change the `main` entry inside `packages.json`.
Actually it's pointing to the minified version of `basicLightbox` which is not good when building. 

It should be better to change it for the the source version: `src/script/main.js`.

Thank you so much

**Comment by jimblue** [comment]
Hi @electerious !

Any news about this?

Thanks man

**Comment by electerious** [comment]
Hey @jimblue how are other browser modules doing it?

I think it won't make a huge difference for a bundle at this size. Maybe we could add the untranspiled version as ["esnext" in the package.json](http://2ality.com/2017/06/pkg-esnext.html).

It's also a default browserify behavior not to transpile files required from `node_modules`. This change may require others (including me) to change their bundling workflow.

**Comment by jimblue** [comment]
Hi @electerious !

Indeed you're lib is so light, it's not about size.

It's to avoid potential problem that happen sometime when concatenating and minify different sources, some already minify other not.

Webpack donc have the same default behaviour.
Also for performance and optimisation it's better to minify everything from source.

And no worries if you prefer keep the actual behaviour, I will survive ! 😉

**Comment by electerious** [comment]
Is the ["esnext" option in the package.json](http://2ality.com/2017/06/pkg-esnext.html) something that would help you? I think it's a fine solution for the current state of JS modules.

**Comment by jimblue** [comment]
@Hi @electerious !

I didn't knew this option, but honestly I don't like it 😄 
Again something to add to webpack...

And I assume peoples using npm are peoples who bundle. That's why main package.json should always be the source...

But that's just my opinion, I will just specify the src path on import.

**Comment by electerious** [comment]
I will stay with the current implementation because it would break my own workflow. But I will keep it in mind and might adjust it one day. Thanks for the suggestion! :)

**Comment by jimblue** [comment]
'right @electerious, no worries about this. 😄
